
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubevirt-csi-tenant
  namespace: argocd
spec:
  generators:
    list:
      elements:
        - clusterName: tenant-cluster1
        - clusterName: tenant-cluster2
  template:
    metadata:
      name: kubevirt-csi-tenant-{{clusterName}}
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/kubevirt/csi-driver
        path: overlays/tenant-cluster/overlay
        targetRevision: main
        directory:
          recurse: true
      destination:
        namespace: kube-system
        server: {{clusterName}}
