apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-csi-tenant-resources
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/kubevirt/csi-driver  # Correct repo URL
    path: deploy/tenant/overlay
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://tenant-cluster-api-endpoint  # Replace with your tenant cluster API endpoint
    namespace: kube-system  # Namespace in the tenant cluster (or relevant namespace)
