apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubevirt-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: csi-driver
          image: quay.io/kubevirt/kubevirt-csi-driver:latest
